LearnMore.Mvc/Controllers/Api/EventsController.cs
using LearnMore.Mvc.Core.Interfaces.Generics;
using Microsoft.AspNet.Identity;
using System.Web.Http;

namespace LearnMore.Mvc.Controllers.Api
{
    [Authorize]
    public class EventsController : ApiController
    {
        private readonly IUnitOfWork _unitOfWork;

        public EventsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpDelete]
        public IHttpActionResult Cancel(int id)
        {
            var userId = User.Identity.GetUserId();
            var evt = _unitOfWork.Events.GetEventWithAttendees(id, userId);

            if (evt == null || evt.IsCanceled)
                return NotFound();

            if (evt.OwnerId != userId)
                return Unauthorized();

            evt.Cancel();

            _unitOfWork.Complete();

            return Ok();
        }
    }
}

LearnMore.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - EventX</title>
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("EventX", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("New Event", "Create", "Events")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - EventX</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @Scripts.Render("~/bundles/app")
    @RenderSection("scripts", required: false)
    <script type="text/x-template" id="notifications-template">
        <ul class="notifications">
            <%
                _.each(notifications, function(notification){
                if (notification.type == 1) { %>
                    <li><span class="highlight"><%= notification.event.owner.name %></span> has canceled the event at <%= notification.event.venue %> at <%= moment(notification.event.dateTime).format("D MMM HH:mm") %>.</li>
                <% }

                else if (notification.type == 2) {
                    var changes = [],
                    originalValues = [],
                    newValues = [];

                    if (notification.originalVenue != notification.event.venue) {
                        changes.push('venue');
                        originalValues.push(notification.originalVenue);
                        newValues.push(notification.event.venue);
                    }

                    if (notification.originalDateTime != notification.event.dateTime) {
                        changes.push('date/time');
                        originalValues.push(moment(notification.originalDateTime).format("D MMM HH:mm"));
                        newValues.push(moment(notification.event.dateTime).format("D MMM HH:mm"));
                    }

                    %>
                    <li><span class="highlight"><%= notification.event.owner.name %></span> has changed the <%= changes.join(' and ') %> of the event from <%= originalValues.join('/') %> to <%= newValues.join('/') %></li>
                    <%
                }
            })
            %>
        </ul>
    </script>
</body>
</html>